# Managed by Hydra

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - data: base
  - model: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_name: testing-pointnext-bsize4
project_root_path: ${hydra:runtime.cwd}
exp_output_root_path: ${project_root_path}/output/${data.dataset}/${model.network.module}/${experiment_name}

global_train_seed: 123
global_test_seed: 321
